version: "3"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "4231:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doodle
volumes:
  postgres-data:
